# Generated by Django 5.0.6 on 2024-07-08 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите категорию', max_length=50, verbose_name='Название категории')),
                ('description', models.TextField(help_text='Добавьте описание категории', verbose_name='Описание категории товара')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование', max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(help_text='Добавьте описание', verbose_name='Описание')),
                ('image_preview', models.ImageField(blank=True, help_text='Загрузите фото товара', null=True, upload_to='products/photo', verbose_name='Фото')),
                ('price', models.FloatField(help_text='Укажите стоимость товара', verbose_name='Стоимость товара')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.category')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ('name',),
            },
        ),
    ]
